name: drug_promation
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.5
  dio: ^4.0.6
  json_annotation: ^4.8.0
  http: ^1.1.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  form_builder_extra_fields: ^10.0.0
  form_builder_file_picker: ^4.0.0
  form_builder_image_picker: ^4.0.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  back_button_interceptor: ^6.0.0
  flutter_secure_storage: ^5.0.2
  awesome_dialog: ^3.0.2
  firebase_messaging: ^14.4.0
  firebase_core: ^2.9.0
  flutter_local_notifications: ^12.0.4
  webview_flutter: ^4.2.0
  qr_code_scanner: ^1.0.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  json_serializable: ^6.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleToFill

flutter:

  uses-material-design: true

  assets:
    - assets/
